<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="Echo.Framework.Core.csproj"/><ProjectReference Include="Echo.Gameplay.csproj"/><Compile Include="../../../Tools/EchoContent/Contracts/*.cs" LinkBase="Contracts"/></ItemGroup></Project>
